/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        transparent: "transparent",
        current: "currentColor",
        blue: {
          primary: "#105bd8",
          "primary-darker": "#0b3d91",
          "primary-darkest": "#061f4a",
          alt: "#02bfe7",
          "alt-darkest": "#046b99",
          "alt-dark": "#00a6d2",
          "alt-light": "#9bdaf1",
          "alt-lightest": "#e1f3f8",
          warm: "#061f4a",
          "warm-light": "#dce4ef",
          cool: "#205493",
          "cool-light": "#4773aa",
          "cool-lighter": "#8ba6ca",
          "cool-lightest": "#dce4ef",
        },
        black: "#212121",
        white: "#ffffff",
        gray: {
          dark: "#323a45",
          default: "#5b616b",
          light: "#aeb0b5",
          lighter: "#d6d7d9",
          lightest: "#f1f1f1",
          "warm-dark": "#494440",
          "warm-light": "#e4e2e0",
          "cool-light": "#dce4ef",
        },
        gold: {
          default: "#ff9d1e",
          light: "#f9aa43",
          lighter: "#ffc375",
          lightest: "#ffebd1",
        },
        green: {
          default: "#2e8540",
          light: "#4aa564",
          lighter: "#94bfa2",
          lightest: "#e7f4e4",
        },
        coolBlue: {
          default: "#205493",
          light: "#4773aa",
          lighter: "#8ba6ca",
          lightest: "#dce4ef",
        },
        secondary: "#dd361c",
        "secondary-darkest": "#99231b",
        "secondary-dark": "#c62d1f",
        "secondary-light": "#e59892",
        "secondary-lightest": "#f9e0de",
        focus: "#aeb0b5",
        visited: "#4c2c92",
      },
    },
  },
  plugins: [],
};
